import type { Apprehension } from './types';

function parseDate(dateString: string): string {
    const parts = dateString.split('/');
    if (parts.length === 3) {
      const [day, month, year] = parts;
      // Ensure parts are valid numbers before creating a date string.
      const yearNum = parseInt(year, 10);
      const monthNum = parseInt(month, 10);
      const dayNum = parseInt(day, 10);

      if (!isNaN(dayNum) && !isNaN(monthNum) && !isNaN(yearNum)) {
         // Pad with leading zeros if necessary
        const monthStr = String(monthNum).padStart(2, '0');
        const dayStr = String(dayNum).padStart(2, '0');
        return `${yearNum}-${monthStr}-${dayStr}`;
      }
    }
    // Return a default or throw an error if the format is incorrect.
    // Using a fixed date for invalid entries ensures consistency.
    return '2024-01-01';
}


const coordinates: { [key: string]: { lat: number, lng: number } } = {
  'CUCUTA': { lat: 7.8939, lng: -72.5078 },
  'PAMPLONA COLOMBIA': { lat: 7.375, lng: -72.647 },
  'CACOTA': { lat: 7.3, lng: -72.6333 },
  'VILLA DEL ROSARIO': { lat: 7.8339, lng: -72.475 },
  'CHITAGA': { lat: 7.15, lng: -72.6667 },
  'MUTISCUA': { lat: 7.2833, lng: -72.7333 },
  'PAMPLONITA': { lat: 7.45, lng: -72.7 },
  'LOS PATIOS': { lat: 7.8425, lng: -72.5322 },
  'BOCHALEMA': { lat: 7.7, lng: -72.65 },
};

const getCoords = (municipality: string, id: string) => {
    const m = municipality.trim().toUpperCase();
    const baseCoords = coordinates[m] || { lat: 7.8939, lng: -72.5078 }; // Default to CUCUTA
    // Create a small, deterministic offset based on the ID to avoid randomness and index dependency
    const idNum = parseInt(id.replace(/\D/g, '').slice(-4) || '0', 10);
    const offset = (idNum % 1000) * 0.00001; // smaller offset
    return { 
        lat: baseCoords.lat + offset, 
        lng: baseCoords.lng + offset 
    };
}

const rawData = [
  {
    "id": "174329",
    "date": "29/10/2024",
    "municipality": "CUCUTA",
    "commune": "3",
    "address": "CLL 18A #9-02 BARRIO LA LIBERTAD",
    "classification": "OTROS",
    "sector": "RESTAURANTE LA LUPE",
    "origin": "GOBERNACION",
    "commercialValue": 0
  },
  {
    "id": "174330",
    "date": "29/10/2024",
    "municipality": "CUCUTA",
    "commune": "3",
    "address": "CLL 18A #9-02  BARRIO LA LIBERTAD",
    "classification": "OTROS",
    "sector": "RESTAURANTE LA LUPE",
    "origin": "GOBERNACION",
    "commercialValue": 0
  },
  {
    "id": "174331",
    "date": "29/10/2024",
    "municipality": "CUCUTA",
    "commune": "3",
    "address": "CLL 18A #9-02 BARRIO LA LIBERTAD",
    "classification": "OTROS",
    "sector": "RESTAURANTE LA LUPE",
    "origin": "GOBERNACION",
    "commercialValue": 0
  },
  {
    "id": "174327",
    "date": "30/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "CLL 6 #18-04 BARERIO ANIVERSARIO II CUCUTA",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "EL SURTIDOR III",
    "origin": "GOBERNACION",
    "commercialValue": 12000
  },
  {
    "id": "174328",
    "date": "30/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "CLL 6 #18-04 ANIVERSARIO II CUCUTA",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "EL SURTIDOR III",
    "origin": "GOBERNACION",
    "commercialValue": 90000
  },
  {
    "id": "174325",
    "date": "30/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "CLL 6A #18-04 ANIVERSARIO II",
    "classification": "CERVEZAS, SIFones, REFAJOS Y MEZCLAS",
    "sector": "EL SURTIDOR III",
    "origin": "GOBERNACION",
    "commercialValue": 50000
  },
  {
    "id": "174326",
    "date": "30/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "Calle 6a # 18-4, Br. Aniversario No 2, Cúcuta, Norte de Santander, Colombia",
    "classification": "OTROS",
    "sector": "EL SURTIDOR III",
    "origin": "GOBERNACION",
    "commercialValue": 76000
  },
  {
    "id": "174324",
    "date": "30/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "CLL 9 #18-04 ANIVERSARIO II CUCUTA",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "ESTANCO HIELOS Y LICORES LA 9",
    "origin": "GOBERNACION",
    "commercialValue": 144000
  },
  {
    "id": "174323",
    "date": "30/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "CLL 9 #18-04 ANIVERSARIO II CUCUTA",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "ESTANCO HIELOS Y LICORES LA 9",
    "origin": "GOBERNACION",
    "commercialValue": 28000
  },
  {
    "id": "174309",
    "date": "30/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AV 14 #11-34 BARRIO TORCOROMA CUCUTA",
    "classification": "OTROS",
    "sector": "TIENDA MECA MARKET",
    "origin": "GOBERNACION",
    "commercialValue": 128000
  },
  {
    "id": "174312",
    "date": "30/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AV 14 #11-34 BARRIO TORCOROMA CUCUTA",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "TIENDA MECA MARKET",
    "origin": "GOBERNACION",
    "commercialValue": 18000
  },
  {
    "id": "174310",
    "date": "30/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AV 14 #11-34 BARRIO TORCOROMA CUCUTA",
    "classification": "OTROS",
    "sector": "TIENDA MECA MARKET",
    "origin": "GOBERNACION",
    "commercialValue": 48000
  },
  {
    "id": "174307",
    "date": "30/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AV 14 #11-34 BARRIO TORCOROMA CUCUTA",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "TIENDA MECA MARKET",
    "origin": "GOBERNACION",
    "commercialValue": 108000
  },
  {
    "id": "174308",
    "date": "30/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AV 14 #11-34 BARRIO TORCOROMA CUCUTA",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "TIENDA MECA MARKET",
    "origin": "GOBERNACION",
    "commercialValue": 128000
  },
  {
    "id": "174311",
    "date": "30/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AV 14 #11-34 BARRIO TORCOROMA CUCUTA",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "TIENDA MECA MARKET",
    "origin": "GOBERNACION",
    "commercialValue": 25000
  },
  {
    "id": "174301",
    "date": "30/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AV 14 #11-34 BARRIO TORCOROMA",
    "classification": "OTROS",
    "sector": "TIENDA MECA MARKET",
    "origin": "GOBERNACION",
    "commercialValue": 128000
  },
  {
    "id": "174300",
    "date": "30/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AV 14 #11-34 BARRIO TORCOROMA CUCUTA",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "TIENDA MECA MARKET",
    "origin": "GOBERNACION",
    "commercialValue": 45000
  },
  {
    "id": "174304",
    "date": "30/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AV 14 #11-34 BARRIO TORCOROMA CUCUTA",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "TIENDA MECA MARKET",
    "origin": "GOBERNACION",
    "commercialValue": 18000
  },
  {
    "id": "174302",
    "date": "30/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AV 14 #11-34 BARRIO TORCOROMA CUCUTA",
    "classification": "OTROS",
    "sector": "TIENDA MECA MARKET",
    "origin": "GOBERNACION",
    "commercialValue": 48000
  },
  {
    "id": "174299",
    "date": "30/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AV 14 #11-34 BARRIO TORCOROMA CUCUTA",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "TIENDA MECA MARKET",
    "origin": "GOBERNACION",
    "commercialValue": 108000
  },
  {
    "id": "174303",
    "date": "30/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AV 14 #11-34 BARRIO TORCOROMA CUCUTA",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "TIENDA MECA MARKET",
    "origin": "GOBERNACION",
    "commercialValue": 25000
  },
  {
    "id": "174276",
    "date": "29/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "MZ D9 LOTE 12 URBANIZACION TORCOROMA II CUCUTA",
    "classification": "OTROS",
    "sector": "ESTANCO BAR LA 17",
    "origin": "GOBERNACION",
    "commercialValue": 150000
  },
  {
    "id": "174277",
    "date": "29/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "MZ D9 LOTE 12 URBANIZACION TORCOROMA II CUCUTA",
    "classification": "OTROS",
    "sector": "ESTANCO BAR LA 17",
    "origin": "GOBERNACION",
    "commercialValue": 84000
  },
  {
    "id": "174275",
    "date": "29/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "MZ D9 LOTE 12 URBANIZACION TORCOROMA II CUCUTA",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "ESTANCO BAR LA 17",
    "origin": "GOBERNACION",
    "commercialValue": 81000
  },
  {
    "id": "174278",
    "date": "29/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "MZ D9 LOTE 12 URBANIZACION TORCOROMA II CUCUTA",
    "classification": "OTROS",
    "sector": "ESTANCO BAR LA 17",
    "origin": "GOBERNACION",
    "commercialValue": 70100
  },
  {
    "id": "174269",
    "date": "29/10/2024",
    "municipality": "CUCUTA",
    "commune": "3",
    "address": "CALLE 16 # 15-34 BARRIO LA LIBERTAD",
    "classification": "OTROS",
    "sector": "SUPERMERCADO LA CANASTA FRESCA SAS",
    "origin": "GOBERNACION",
    "commercialValue": 263000
  },
  {
    "id": "174270",
    "date": "29/10/2024",
    "municipality": "CUCUTA",
    "commune": "3",
    "address": "CALLE 16 # 15-34 LA LIBERTAD CUCUTA",
    "classification": "OTROS",
    "sector": "SUPERMERCADO LA CANASTA FRESCA SAS",
    "origin": "GOBERNACION",
    "commercialValue": 178500
  },
  {
    "id": "174262",
    "date": "29/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AV B # 11-71 URBANIZACION ANIVERSARIO I",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "MERCABASTOS LOS MELOS",
    "origin": "GOBERNACION",
    "commercialValue": 24500
  },
  {
    "id": "174261",
    "date": "29/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AV B # 11-71 URBANIZACION ANIVERSARIO I",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "MERCABASTOS LOS MELOS",
    "origin": "GOBERNACION",
    "commercialValue": 21000
  },
  {
    "id": "174264",
    "date": "29/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AV B # 11-71 URBANIZACION ANIVERSARIO I",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "MERCABASTOS LOS MELOS",
    "origin": "GOBERNACION",
    "commercialValue": 30000
  },
  {
    "id": "174263",
    "date": "29/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AV B # 11-71 URBANIZACION ANIVERSARIO I",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "MERCABASTOS LOS MELOS",
    "origin": "GOBERNACION",
    "commercialValue": 45000
  },
  {
    "id": "174260",
    "date": "29/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AV B # 11-71 URBANIZACION ANIVERSARIO I",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "MERCABASTOS LOS MELOS",
    "origin": "GOBERNACION",
    "commercialValue": 28000
  },
  {
    "id": "174259",
    "date": "29/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AV B # 11-71 URBANIZACION ANIVERSARIO I",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "MERCABASTOS LOS MELOS",
    "origin": "GOBERNACION",
    "commercialValue": 27000
  },
  {
    "id": "174258",
    "date": "29/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AV B # 11-71 URBANIZACION ANIVERSARIO I",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "MERCABASTOS LOS MELOS",
    "origin": "GOBERNACION",
    "commercialValue": 36000
  },
  {
    "id": "174248",
    "date": "29/10/2024",
    "municipality": "CUCUTA",
    "commune": "3",
    "address": "CALLE 16 # 10-75 BARRIO LA LIBERTAD CUCUTA",
    "classification": "OTROS",
    "sector": "ANA DOLORES PAREDES SANTIAGO",
    "origin": "GOBERNACION",
    "commercialValue": 117000
  },
  {
    "id": "174249",
    "date": "29/10/2024",
    "municipality": "CUCUTA",
    "commune": "3",
    "address": "CALLE 16 # 10-75 BARRIO LA LIBERTAD CUCUTA",
    "classification": "OTROS",
    "sector": "ANA DOLORES PAREDES SANTIAGO",
    "origin": "GOBERNACION",
    "commercialValue": 12000
  },
  {
    "id": "174244",
    "date": "29/10/2024",
    "municipality": "CUCUTA",
    "commune": "3",
    "address": "CALLE 1a  # 8-77  BARRIO LA LIBERTAD CUCUTA",
    "classification": "OTROS",
    "sector": "SUPERMERCADO  JOHANNA PLUS",
    "origin": "GOBERNACION",
    "commercialValue": 100000
  },
  {
    "id": "174235",
    "date": "29/10/2024",
    "municipality": "CUCUTA",
    "commune": "3",
    "address": "CALLE 3 # 2-65 BARRIO BOGOTA",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "TIENDA LAS GEMELAS",
    "origin": "GOBERNACION",
    "commercialValue": 3000
  },
  {
    "id": "174239",
    "date": "29/10/2024",
    "municipality": "CUCUTA",
    "commune": "3",
    "address": "CALLE 3 # 2-65 BARRIO BOGOTA",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "TIENDA LAS GEMELAS",
    "origin": "GOBERNACION",
    "commercialValue": 18000
  },
  {
    "id": "174238",
    "date": "29/10/2024",
    "municipality": "CUCUTA",
    "commune": "3",
    "address": "CALLE 3 # 2-65 BARRIO BOGOTA",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "TIENDA LAS GEMELAS",
    "origin": "GOBERNACION",
    "commercialValue": 9000
  },
  {
    "id": "174236",
    "date": "29/10/2024",
    "municipality": "CUCUTA",
    "commune": "3",
    "address": "CALLE 3 # 2-65 BARRIO BOGOTA",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "TIENDA LAS GEMELAS",
    "origin": "GOBERNACION",
    "commercialValue": 12000
  },
  {
    "id": "174237",
    "date": "29/10/2024",
    "municipality": "CUCUTA",
    "commune": "3",
    "address": "CALLE 3 # 2-65 BARRIO BOGOTA",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "TIENDA LAS GEMELAS",
    "origin": "GOBERNACION",
    "commercialValue": 3000
  },
  {
    "id": "174224",
    "date": "28/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AVENIDA 6 # 8N-147 SAN MARTIN",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "TIENDA MIXTA SAN MARTIN",
    "origin": "GOBERNACION",
    "commercialValue": 24000
  },
  {
    "id": "174223",
    "date": "28/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AVENIDA 6 # 8N-147 SAN MARTIN",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "TIENDA MIXTA SAN MARTIN",
    "origin": "GOBERNACION",
    "commercialValue": 3000
  },
  {
    "id": "174216",
    "date": "28/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AVENIDA 6 # 10N-10 SAN MARTIN",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "TIENDA MIXTA  LA ESQUINA DE AYDEE",
    "origin": "GOBERNACION",
    "commercialValue": 12000
  },
  {
    "id": "174215",
    "date": "28/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AVENIDA 6 # 10N-10 SAN MARTIN",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "TIENDA MIXTA  LA ESQUINA DE AYDEE",
    "origin": "GOBERNACION",
    "commercialValue": 12000
  },
  {
    "id": "174217",
    "date": "28/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AVENIDA 6 # 10N-10 SAN MARTIN",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "TIENDA MIXTA  LA ESQUINA DE AYDEE",
    "origin": "GOBERNACION",
    "commercialValue": 27000
  },
  {
    "id": "174211",
    "date": "25/10/2024",
    "municipality": "CUCUTA",
    "commune": "5",
    "address": "AV 7 # 5-12 BARRIO SEVILLA",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "TIENDA JB EL WICHO",
    "origin": "GOBERNACION",
    "commercialValue": 207000
  },
  {
    "id": "174210",
    "date": "25/10/2024",
    "municipality": "CUCUTA",
    "commune": "5",
    "address": "AV 7 # 5-12 BARRIO SEVILLA",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "TIENDA JB EL WICHO",
    "origin": "GOBERNACION",
    "commercialValue": 30000
  },
  {
    "id": "174214",
    "date": "25/10/2024",
    "municipality": "CUCUTA",
    "commune": "5",
    "address": "AV 7 # 5-12 BARRIO SEVILLA",
    "classification": "OTROS",
    "sector": "TIENDA JB EL WICHO",
    "origin": "GOBERNACION",
    "commercialValue": 13000
  },
  {
    "id": "174212",
    "date": "25/10/2024",
    "municipality": "CUCUTA",
    "commune": "5",
    "address": "AV 7 # 5-12 BARRIO SEVILLA",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "TIENDA JB EL WICHO",
    "origin": "GOBERNACION",
    "commercialValue": 36400
  },
  {
    "id": "174213",
    "date": "25/10/2024",
    "municipality": "CUCUTA",
    "commune": "5",
    "address": "AV 7 # 5-12 BARRIO SEVILLA",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "TIENDA JB EL WICHO",
    "origin": "GOBERNACION",
    "commercialValue": 33000
  },
  {
    "id": "174209",
    "date": "25/10/2024",
    "municipality": "CUCUTA",
    "commune": "5",
    "address": "AV 7 # 5-12 BARRIO SEVILLA",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "TIENDA JB EL WICHO",
    "origin": "GOBERNACION",
    "commercialValue": 30000
  },
  {
    "id": "174204",
    "date": "25/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AV 4 # 5-97 BAJO PAMPLONITA",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "POOLES EL RINCON DE ZAZA",
    "origin": "GOBERNACION",
    "commercialValue": 12500
  },
  {
    "id": "174202",
    "date": "25/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AV 4 # 5-97 BAJO PAMPLONITA",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "POOLES EL RINCON DE ZAZA",
    "origin": "GOBERNACION",
    "commercialValue": 6000
  },
  {
    "id": "174199",
    "date": "25/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AV 4 # 5-97 BAJO PAMPLONITA",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "POOLES EL RINCON DE ZAZA",
    "origin": "GOBERNACION",
    "commercialValue": 6000
  },
  {
    "id": "174200",
    "date": "25/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AV 4 # 5-97 BAJO PAMPLONITA",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "POOLES EL RINCON DE ZAZA",
    "origin": "GOBERNACION",
    "commercialValue": 24000
  },
  {
    "id": "174201",
    "date": "25/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AV 4 # 5-97 BAJO PAMPLONITA",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "POOLES EL RINCON DE ZAZA",
    "origin": "GOBERNACION",
    "commercialValue": 18000
  },
  {
    "id": "174207",
    "date": "25/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AV 4 # 5-97 BAJO PAMPLONITA",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "POOLES EL RINCON DE ZAZA",
    "origin": "GOBERNACION",
    "commercialValue": 17500
  },
  {
    "id": "174197",
    "date": "25/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AV 4 # 5-97 BAJO PAMPLONITA",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "POOLES EL RINCON DE ZAZA",
    "origin": "GOBERNACION",
    "commercialValue": 24000
  },
  {
    "id": "174206",
    "date": "25/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AV 4 # 5-97 BAJO PAMPLONITA",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "POOLES EL RINCON DE ZAZA",
    "origin": "GOBERNACION",
    "commercialValue": 75600
  },
  {
    "id": "174203",
    "date": "25/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AV 4 # 5-97 BAJO PAMPLONITA",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "POOLES EL RINCON DE ZAZA",
    "origin": "GOBERNACION",
    "commercialValue": 17500
  },
  {
    "id": "174205",
    "date": "25/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AV 4 # 5-97 BAJO PAMPLONITA",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "POOLES EL RINCON DE ZAZA",
    "origin": "GOBERNACION",
    "commercialValue": 48000
  },
  {
    "id": "174198",
    "date": "25/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AV 4 # 5-97 BAJO PAMPLONITA",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "POOLES EL RINCON DE ZAZA",
    "origin": "GOBERNACION",
    "commercialValue": 30000
  },
  {
    "id": "174208",
    "date": "25/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AV 4 # 5-97 BAJO PAMPLONITA",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "POOLES EL RINCON DE ZAZA",
    "origin": "GOBERNACION",
    "commercialValue": 20000
  },
  {
    "id": "174194",
    "date": "25/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "CALLE 7 # 6-73 SAN LUIS",
    "classification": "OTROS",
    "sector": "MINI MERCADO  EL HIGUERON",
    "origin": "GOBERNACION",
    "commercialValue": 165000
  },
  {
    "id": "174195",
    "date": "25/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "CALLE 7 # 6-73 SAN LUIS",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "MINI MERCADO  EL HIGUERON",
    "origin": "GOBERNACION",
    "commercialValue": 72000
  },
  {
    "id": "174193",
    "date": "23/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AVENIDA 3 # 17-64 BARRIO SAN LUIS",
    "classification": "OTROS",
    "sector": "SUPERMERCADO LA REBAJA DE SAN LUIS",
    "origin": "GOBERNACION",
    "commercialValue": 160000
  },
  {
    "id": "174192",
    "date": "23/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AVENIDA 3 # 17-64 BARRIO SAN LUIS",
    "classification": "OTROS",
    "sector": "SUPERMERCADO LA REBAJA DE SAN LUIS",
    "origin": "GOBERNACION",
    "commercialValue": 32000
  },
  {
    "id": "174185",
    "date": "23/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AV  3 # 18-59 SAN LUIS",
    "classification": "OTROS",
    "sector": "DISTRIBUCIONES FERCHO RUEDA",
    "origin": "GOBERNACION",
    "commercialValue": 63000
  },
  {
    "id": "174184",
    "date": "23/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AV  3 # 18-59 SAN LUIS",
    "classification": "OTROS",
    "sector": "DISTRIBUCIONES FERCHO RUEDA",
    "origin": "GOBERNACION",
    "commercialValue": 210000
  },
  {
    "id": "174140",
    "date": "23/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AV 1 N 20-51",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "MERKA CRIPKER",
    "origin": "GOBERNACION",
    "commercialValue": 23100
  },
  {
    "id": "174139",
    "date": "23/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AV 1 N 20-51",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "MERKA CRIPKER",
    "origin": "GOBERNACION",
    "commercialValue": 35100
  },
  {
    "id": "174138",
    "date": "23/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AV 1 N 20-51",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "MERKA CRIPKER",
    "origin": "GOBERNACION",
    "commercialValue": 51000
  },
  {
    "id": "174128",
    "date": "23/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "CLL 20 #1A-14 BOSQUES DE PAMPLONITA",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "MINIMERCADO MERCABUENO",
    "origin": "GOBERNACION",
    "commercialValue": 30000
  },
  {
    "id": "174124",
    "date": "22/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "AV 3E #7-05 BARRIO POPULAR",
    "classification": "OTROS",
    "sector": "MINI ABASTOS MARIA AUXILIADORA",
    "origin": "GOBERNACION",
    "commercialValue": 13800
  },
  {
    "id": "174123",
    "date": "22/10/2024",
    "municipality": "CUCUTA",
    "commune": "2",
    "address": "AV 3E #7-05 BARRIO POPULAR",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "MINI ABASTOS MARIA AUXILIADORA",
    "origin": "GOBERNACION",
    "commercialValue": 6200
  },
  {
    "id": "174125",
    "date": "22/10/2024",
    "municipality": "CUCUTA",
    "commune": "2",
    "address": "AV 3E #7-05 BARRIO POPULAR",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "MINI ABASTOS MARIA AUXILIADORA",
    "origin": "GOBERNACION",
    "commercialValue": 17600
  },
  {
    "id": "174127",
    "date": "22/10/2024",
    "municipality": "CUCUTA",
    "commune": "2",
    "address": "AV 3E #7-05 BARRIO POPULAR",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "MINI ABASTOS MARIA AUXILIADORA",
    "origin": "GOBERNACION",
    "commercialValue": 3000
  },
  {
    "id": "174126",
    "date": "22/10/2024",
    "municipality": "CUCUTA",
    "commune": "2",
    "address": "AV 3E #7-05 BARRIO POPULAR",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "MINI ABASTOS MARIA AUXILIADORA",
    "origin": "GOBERNACION",
    "commercialValue": 172500
  },
  {
    "id": "174122",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRR 6 #7-86 CLL REAL 2DO PISO",
    "classification": "OTROS",
    "sector": "LA ROMANA CLUB",
    "origin": "GOBERNACION",
    "commercialValue": 80000
  },
  {
    "id": "174120",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRR 6 #7-86 CLL REAL 2DO PISO",
    "classification": "OTROS",
    "sector": "LA ROMANA CLUB",
    "origin": "GOBERNACION",
    "commercialValue": 70000
  },
  {
    "id": "174121",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRR 6 #7-86 CLL REAL 2DO PISO",
    "classification": "OTROS",
    "sector": "LA ROMANA CLUB",
    "origin": "GOBERNACION",
    "commercialValue": 90000
  },
  {
    "id": "174119",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRR 7 #2-25 LC 1 EL HUMILLADERO",
    "classification": "OTROS",
    "sector": "TIENDA LOS RECUERDOS DE ELLA",
    "origin": "GOBERNACION",
    "commercialValue": 0
  },
  {
    "id": "174118",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRR 7 #2-25 LC 1 EL HUMILLADERO",
    "classification": "OTROS",
    "sector": "TIENDA LOS RECUERDOS DE ELLA",
    "origin": "GOBERNACION",
    "commercialValue": 0
  },
  {
    "id": "174117",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRR 7 #2-25 LC 1 EL HUMILLADERO",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "TIENDA LOS RECUERDOS DE ELLA",
    "origin": "GOBERNACION",
    "commercialValue": 159000
  },
  {
    "id": "174116",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRR 7 #2-25 LC 1 EL HUMILLADERO",
    "classification": "OTROS",
    "sector": "TIENDA LOS RECUERDOS DE ELLA",
    "origin": "GOBERNACION",
    "commercialValue": 450000
  },
  {
    "id": "174105",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CALLE 3 N 8 - 73",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "AUTO TIENDA LOS CEREZOS",
    "origin": "GOBERNACION",
    "commercialValue": 4050
  },
  {
    "id": "174106",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CALLE 3 N 8 - 73",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "AUTO TIENDA LOS CEREZOS",
    "origin": "GOBERNACION",
    "commercialValue": 3300
  },
  {
    "id": "174101",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CALLE 3 N 8 - 73",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "AUTO TIENDA LOS CEREZOS",
    "origin": "GOBERNACION",
    "commercialValue": 4950
  },
  {
    "id": "174111",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CALLE 3 N 8 - 73",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "AUTO TIENDA LOS CEREZOS",
    "origin": "GOBERNACION",
    "commercialValue": 42000
  },
  {
    "id": "174107",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CALLE 3 N 8 - 73",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "AUTO TIENDA LOS CEREZOS",
    "origin": "GOBERNACION",
    "commercialValue": 3000
  },
  {
    "id": "174098",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CALLE 3 N 8 - 73",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "AUTO TIENDA LOS CEREZOS",
    "origin": "GOBERNACION",
    "commercialValue": 15000
  },
  {
    "id": "174108",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CALLE 3 N 8 - 73",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "AUTO TIENDA LOS CEREZOS",
    "origin": "GOBERNACION",
    "commercialValue": 3000
  },
  {
    "id": "174109",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CALLE 3 N 8 - 73",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "AUTO TIENDA LOS CEREZOS",
    "origin": "GOBERNACION",
    "commercialValue": 84500
  },
  {
    "id": "174112",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CALLE 3 N 8 - 73",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "AUTO TIENDA LOS CEREZOS",
    "origin": "GOBERNACION",
    "commercialValue": 30800
  },
  {
    "id": "174104",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CALLE 3 N 8 - 73",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "AUTO TIENDA LOS CEREZOS",
    "origin": "GOBERNACION",
    "commercialValue": 3000
  },
  {
    "id": "174114",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CALLE 3 N 8 - 73",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "AUTO TIENDA LOS CEREZOS",
    "origin": "GOBERNACION",
    "commercialValue": 253500
  },
  {
    "id": "174115",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CALLE 3 N 8 - 73",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "AUTO TIENDA LOS CEREZOS",
    "origin": "GOBERNACION",
    "commercialValue": 9000
  },
  {
    "id": "174103",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CALLE 3 N 8 - 73",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "AUTO TIENDA LOS CEREZOS",
    "origin": "GOBERNACION",
    "commercialValue": 3000
  },
  {
    "id": "174099",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CALLE 3 N 8 - 73",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "AUTO TIENDA LOS CEREZOS",
    "origin": "GOBERNACION",
    "commercialValue": 9000
  },
  {
    "id": "174110",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CALLE 3 N 8 - 73",
    "classification": "OTROS",
    "sector": "AUTO TIENDA LOS CEREZOS",
    "origin": "GOBERNACION",
    "commercialValue": 12000
  },
  {
    "id": "174100",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CALLE 3 N 8 - 73",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "AUTO TIENDA LOS CEREZOS",
    "origin": "GOBERNACION",
    "commercialValue": 93000
  },
  {
    "id": "174113",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CALLE 3 N 8 - 73",
    "classification": "OTROS",
    "sector": "AUTO TIENDA LOS CEREZOS",
    "origin": "GOBERNACION",
    "commercialValue": 15000
  },
  {
    "id": "174102",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CALLE 3 N 8 - 73",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "AUTO TIENDA LOS CEREZOS",
    "origin": "GOBERNACION",
    "commercialValue": 6000
  },
  {
    "id": "174097",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRR 6 #4-03 CENTRO",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "SUPER MAYORISTA DIAMANTE S.A.S.",
    "origin": "GOBERNACION",
    "commercialValue": 75000
  },
  {
    "id": "174096",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRR 6 #4-03 CENTRO",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "SUPER MAYORISTA DIAMANTE S.A.S.",
    "origin": "GOBERNACION",
    "commercialValue": 24000
  },
  {
    "id": "174094",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRR 6 #4-03 CENTRO",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "SUPER MAYORISTA DIAMANTE S.A.S.",
    "origin": "GOBERNACION",
    "commercialValue": 24000
  },
  {
    "id": "174095",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRR 6 #4-03 CENTRO",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "SUPER MAYORISTA DIAMANTE S.A.S.",
    "origin": "GOBERNACION",
    "commercialValue": 75000
  },
  {
    "id": "174080",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRR 6 #8-27 CENTRO",
    "classification": "OTROS",
    "sector": "EL REFUGIO CAFE DISCO BAR",
    "origin": "GOBERNACION",
    "commercialValue": 60000
  },
  {
    "id": "174077",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRR 6 #8-27 CENTRO",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "EL REFUGIO CAFE DISCO BAR",
    "origin": "GOBERNACION",
    "commercialValue": 125000
  },
  {
    "id": "174088",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRR 6 #8-27 CENTRO",
    "classification": "OTROS",
    "sector": "EL REFUGIO CAFE DISCO BAR",
    "origin": "GOBERNACION",
    "commercialValue": 105000
  },
  {
    "id": "174082",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRR 6 #8-27 CENTRO",
    "classification": "OTROS",
    "sector": "EL REFUGIO CAFE DISCO BAR",
    "origin": "GOBERNACION",
    "commercialValue": 90000
  },
  {
    "id": "174092",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRR 6 #8-27 CENTRO",
    "classification": "OTROS",
    "sector": "EL REFUGIO CAFE DISCO BAR",
    "origin": "GOBERNACION",
    "commercialValue": 70100
  },
  {
    "id": "174086",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRR 6 #8-27 CENTRO",
    "classification": "OTROS",
    "sector": "EL REFUGIO CAFE DISCO BAR",
    "origin": "GOBERNACION",
    "commercialValue": 190000
  },
  {
    "id": "174089",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRR 6 #8-27 CENTRO",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "EL REFUGIO CAFE DISCO BAR",
    "origin": "GOBERNACION",
    "commercialValue": 22400
  },
  {
    "id": "174083",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRR 6 #8-27 CENTRO",
    "classification": "OTROS",
    "sector": "EL REFUGIO CAFE DISCO BAR",
    "origin": "GOBERNACION",
    "commercialValue": 70000
  },
  {
    "id": "174087",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRR 6 #8-27 CENTRO",
    "classification": "OTROS",
    "sector": "EL REFUGIO CAFE DISCO BAR",
    "origin": "GOBERNACION",
    "commercialValue": 80000
  },
  {
    "id": "174081",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRR 6 #8-27 CENTRO",
    "classification": "OTROS",
    "sector": "EL REFUGIO CAFE DISCO BAR",
    "origin": "GOBERNACION",
    "commercialValue": 35000
  },
  {
    "id": "174090",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRR 6 #8-27 CENTRO",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "EL REFUGIO CAFE DISCO BAR",
    "origin": "GOBERNACION",
    "commercialValue": 21000
  },
  {
    "id": "174091",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRR 6 #8-27 CENTRO",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "EL REFUGIO CAFE DISCO BAR",
    "origin": "GOBERNACION",
    "commercialValue": 17500
  },
  {
    "id": "174079",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRR 6 #8-27 CENTRO",
    "classification": "OTROS",
    "sector": "EL REFUGIO CAFE DISCO BAR",
    "origin": "GOBERNACION",
    "commercialValue": 73900
  },
  {
    "id": "174084",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRR 6 #8-27 CENTRO",
    "classification": "OTROS",
    "sector": "EL REFUGIO CAFE DISCO BAR",
    "origin": "GOBERNACION",
    "commercialValue": 45000
  },
  {
    "id": "174078",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRR 6 #8-27 CENTRO",
    "classification": "OTROS",
    "sector": "EL REFUGIO CAFE DISCO BAR",
    "origin": "GOBERNACION",
    "commercialValue": 125000
  },
  {
    "id": "174085",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRR 6 #8-27 CENTRO",
    "classification": "OTROS",
    "sector": "EL REFUGIO CAFE DISCO BAR",
    "origin": "GOBERNACION",
    "commercialValue": 60000
  },
  {
    "id": "174093",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRR 6 #8-27 CENTRO",
    "classification": "OTROS",
    "sector": "EL REFUGIO CAFE DISCO BAR",
    "origin": "GOBERNACION",
    "commercialValue": 28000
  },
  {
    "id": "174075",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRR 9 LC 201 CC EL RECREO",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "COCO BONGO",
    "origin": "GOBERNACION",
    "commercialValue": 3000
  },
  {
    "id": "174076",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRR 9 LC 201 CC EL RECREO",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "COCO BONGO",
    "origin": "GOBERNACION",
    "commercialValue": 3000
  },
  {
    "id": "174073",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRR 9 LC 201 CC EL RECREO",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "COCO BONGO",
    "origin": "GOBERNACION",
    "commercialValue": 20000
  },
  {
    "id": "174074",
    "date": "19/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRR 9 LC 201 CC EL RECREO",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "COCO BONGO",
    "origin": "GOBERNACION",
    "commercialValue": 3000
  },
  {
    "id": "174070",
    "date": "18/10/2024",
    "municipality": "CACOTA",
    "commune": "54125",
    "address": "NOA LC 1 CENTRO",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "TIENDA DARY",
    "origin": "GOBERNACION",
    "commercialValue": 21000
  },
  {
    "id": "174071",
    "date": "18/10/2024",
    "municipality": "CACOTA",
    "commune": "54125",
    "address": "NOA LC 1 CENTRO",
    "classification": "OTROS",
    "sector": "TIENDA DARY",
    "origin": "GOBERNACION",
    "commercialValue": 124000
  },
  {
    "id": "174069",
    "date": "18/10/2024",
    "municipality": "CACOTA",
    "commune": "54125",
    "address": "NOA LC 1 CENTRO",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "TIENDA DARY",
    "origin": "GOBERNACION",
    "commercialValue": 30000
  },
  {
    "id": "174072",
    "date": "18/10/2024",
    "municipality": "CACOTA",
    "commune": "54125",
    "address": "NOA LC 1 CENTRO",
    "classification": "OTROS",
    "sector": "TIENDA DARY",
    "origin": "GOBERNACION",
    "commercialValue": 19000
  },
  {
    "id": "174068",
    "date": "18/10/2024",
    "municipality": "CACOTA",
    "commune": "54125",
    "address": "NOA LC 1 CENTRO",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "TIENDA DARY",
    "origin": "GOBERNACION",
    "commercialValue": 30000
  },
  {
    "id": "174066",
    "date": "18/10/2024",
    "municipality": "CACOTA",
    "commune": "54125",
    "address": "CRR 3 #3-10 CENTRO",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "TIENDA PAO PAO",
    "origin": "GOBERNACION",
    "commercialValue": 350000
  },
  {
    "id": "174067",
    "date": "18/10/2024",
    "municipality": "CACOTA",
    "commune": "54125",
    "address": "CRR 3 #3-10 CENTRO",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "TIENDA PAO PAO",
    "origin": "GOBERNACION",
    "commercialValue": 9900
  },
  {
    "id": "174065",
    "date": "18/10/2024",
    "municipality": "CACOTA",
    "commune": "54125",
    "address": "CRR 3 #3-10 CENTRO",
    "classification": "OTROS",
    "sector": "TIENDA PAO PAO",
    "origin": "GOBERNACION",
    "commercialValue": 228000
  },
  {
    "id": "174059",
    "date": "18/10/2024",
    "municipality": "CACOTA",
    "commune": "54125",
    "address": "CRA 3 N 3-21",
    "classification": "OTROS",
    "sector": "TIENDA LA CACOTEÑA",
    "origin": "GOBERNACION",
    "commercialValue": 90000
  },
  {
    "id": "174063",
    "date": "18/10/2024",
    "municipality": "CACOTA",
    "commune": "54125",
    "address": "CRA 3 N 3-21",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "TIENDA LA CACOTEÑA",
    "origin": "GOBERNACION",
    "commercialValue": 4400
  },
  {
    "id": "174057",
    "date": "18/10/2024",
    "municipality": "CACOTA",
    "commune": "54125",
    "address": "CRA 3 N 3-21",

    "classification": "OTROS",
    "sector": "TIENDA LA CACOTEÑA",
    "origin": "GOBERNACION",
    "commercialValue": 70000
  },
  {
    "id": "174058",
    "date": "18/10/2024",
    "municipality": "CACOTA",
    "commune": "54125",
    "address": "CRA 3 N 3-21",
    "classification": "OTROS",
    "sector": "TIENDA LA CACOTEÑA",
    "origin": "GOBERNACION",
    "commercialValue": 30000
  },
  {
    "id": "174060",
    "date": "18/10/2024",
    "municipality": "CACOTA",
    "commune": "54125",
    "address": "CRA 3 N 3-21",
    "classification": "OTROS",
    "sector": "TIENDA LA CACOTEÑA",
    "origin": "GOBERNACION",
    "commercialValue": 10000
  },
  {
    "id": "174064",
    "date": "18/10/2024",
    "municipality": "CACOTA",
    "commune": "54125",
    "address": "CRA 3 N 3-21",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "TIENDA LA CACOTEÑA",
    "origin": "GOBERNACION",
    "commercialValue": 5600
  },
  {
    "id": "174061",
    "date": "18/10/2024",
    "municipality": "CACOTA",
    "commune": "54125",
    "address": "CRA 3 N 3-21",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "TIENDA LA CACOTEÑA",
    "origin": "GOBERNACION",
    "commercialValue": 10000
  },
  {
    "id": "174062",
    "date": "18/10/2024",
    "municipality": "CACOTA",
    "commune": "54125",
    "address": "CRA 3 N 3-21",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "TIENDA LA CACOTEÑA",
    "origin": "GOBERNACION",
    "commercialValue": 12500
  },
  {
    "id": "174056",
    "date": "18/10/2024",
    "municipality": "CACOTA",
    "commune": "54125",
    "address": "CRR 3 #2-32 BARRIO CALLE REAL",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "BILLARES LA REAL",
    "origin": "GOBERNACION",
    "commercialValue": 37200
  },
  {
    "id": "174055",
    "date": "25/10/2024",
    "municipality": "VILLA DEL ROSARIO",
    "commune": "54874",
    "address": "CLL 19 #2-231 PISO 1 LC 1 LOMITAS DEL TRAPICHE",
    "classification": "OTROS",
    "sector": "PAPALECO S.A.S.",
    "origin": "GOBERNACION",
    "commercialValue": 24600
  },
  {
    "id": "174052",
    "date": "25/10/2024",
    "municipality": "VILLA DEL ROSARIO",
    "commune": "54874",
    "address": "CLL 19 #2-231 PISO 1 LC 1 LOMITAS DEL TRAPICHE",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "PAPALECO S.A.S.",
    "origin": "GOBERNACION",
    "commercialValue": 24000
  },
  {
    "id": "174054",
    "date": "25/10/2024",
    "municipality": "VILLA DEL ROSARIO",
    "commune": "54874",
    "address": "CLL 19 #2-231 PISO 1 LC 1 LOMITAS DEL TRAPICHE",
    "classification": "OTROS",
    "sector": "PAPALECO S.A.S.",
    "origin": "GOBERNACION",
    "commercialValue": 24600
  },
  {
    "id": "174053",
    "date": "25/10/2024",
    "municipality": "VILLA DEL ROSARIO",
    "commune": "54874",
    "address": "CLL 19 #2-231 PISO 1 LC 1 LOMITAS DEL TRAPICHE",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "PAPALECO S.A.S.",
    "origin": "GOBERNACION",
    "commercialValue": 72000
  },
  {
    "id": "174050",
    "date": "18/10/2024",
    "municipality": "CUCUTA",
    "commune": "2",
    "address": "Av 18 N 0 -10 LOCAL 4",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "SURTI CERVEZA PACHECO S.A.S",
    "origin": "GOBERNACION",
    "commercialValue": 256000
  },
  {
    "id": "174051",
    "date": "18/10/2024",
    "municipality": "CUCUTA",
    "commune": "2",
    "address": "Av 18 N 0 -10 LOCAL 4",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "SURTI CERVEZA PACHECO S.A.S",
    "origin": "GOBERNACION",
    "commercialValue": 25000
  },
  {
    "id": "174049",
    "date": "18/10/2024",
    "municipality": "CHITAGA",
    "commune": "54174",
    "address": "CLL 9 #5-59 EL CARMEN",
    "classification": "OTROS",
    "sector": "TIENDA MIXTA LOS 3 AMIGOS CHITAGA",
    "origin": "GOBERNACION",
    "commercialValue": 90000
  },
  {
    "id": "174047",
    "date": "18/10/2024",
    "municipality": "CHITAGA",
    "commune": "54174",
    "address": "CRR 7 #4-65 CHITAGA",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "BILLARES DOS PASAJES",
    "origin": "GOBERNACION",
    "commercialValue": 24000
  },
  {
    "id": "174048",
    "date": "18/10/2024",
    "municipality": "CHITAGA",
    "commune": "54174",
    "address": "CRR 7 #4-65 CHITAGA",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "BILLARES DOS PASAJES",
    "origin": "GOBERNACION",
    "commercialValue": 6000
  },
  {
    "id": "174046",
    "date": "17/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRR 5 # CALLE 9 LA CHOZA",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "ELITE GEMAR",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 3000
  },
  {
    "id": "174041",
    "date": "17/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRR 5 # CALLE 9 LA CHOZA",
    "classification": "OTROS",
    "sector": "ELITE GEMAR",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 200000
  },
  {
    "id": "174044",
    "date": "17/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRR 5 # CALLE 9 LA CHOZA",
    "classification": "OTROS",
    "sector": "ELITE GEMAR",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 120000
  },
  {
    "id": "174043",
    "date": "17/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRR 5 # CALLE 9 LA CHOZA",
    "classification": "OTROS",
    "sector": "ELITE GEMAR",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 90000
  },
  {
    "id": "174045",
    "date": "17/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRR 5 # CALLE 9 LA CHOZA",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "ELITE GEMAR",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 57000
  },
  {
    "id": "174042",
    "date": "17/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRR 5 # CALLE 9 LA CHOZA",
    "classification": "OTROS",
    "sector": "ELITE GEMAR",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 90000
  },
  {
    "id": "174040",
    "date": "17/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRA 5 N -08",
    "classification": "OTROS",
    "sector": "DELIKATESENS LA MEJOR",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 78000
  },
  {
    "id": "174033",
    "date": "17/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRA 5 N -08",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "DELIKATESENS LA MEJOR",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 504000
  },
  {
    "id": "174038",
    "date": "17/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRA 5 N -08",
    "classification": "OTROS",
    "sector": "DELIKATESENS LA MEJOR",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 284000
  },
  {
    "id": "174032",
    "date": "17/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRA 5 N -08",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "DELIKATESENS LA MEJOR",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 162000
  },
  {
    "id": "174037",
    "date": "17/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRA 5 N -08",
    "classification": "OTROS",
    "sector": "DELIKATESENS LA MEJOR",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 150000
  },
  {
    "id": "174034",
    "date": "17/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRA 5 N -08",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "DELIKATESENS LA MEJOR",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 270000
  },
  {
    "id": "174036",
    "date": "17/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRA 5 N -08",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "DELIKATESENS LA MEJOR",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 250000
  },
  {
    "id": "174035",
    "date": "17/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRA 5 N -08",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "DELIKATESENS LA MEJOR",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 240000
  },
  {
    "id": "174030",
    "date": "17/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CLL 9 #5-29 CENTRO",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "CONTRERAS DISCO BAR",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 280000
  },
  {
    "id": "174031",
    "date": "17/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CLL 9 #5-29 CENTRO",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "CONTRERAS DISCO BAR",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 43000
  },
  {
    "id": "174028",
    "date": "17/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRA 5 N 6-37",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "DISTRIBUCIONES LA GUACA",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 36000
  },
  {
    "id": "174029",
    "date": "17/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRA 5 N 6-37",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "DISTRIBUCIONES LA GUACA",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 18600
  },
  {
    "id": "174027",
    "date": "16/10/2024",
    "municipality": "MUTISCUA",
    "commune": "54480",
    "address": "CALLE 3N 8-38",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "RESTAURANTE YOLY",
    "origin": "GOBERNACION",
    "commercialValue": 15500
  },
  {
    "id": "174026",
    "date": "16/10/2024",
    "municipality": "MUTISCUA",
    "commune": "54480",
    "address": "CALLE 3N 8-38",
    "classification": "CREMA DE LICOR",
    "sector": "RESTAURANTE YOLY",
    "origin": "GOBERNACION",
    "commercialValue": 210000
  },
  {
    "id": "174025",
    "date": "16/10/2024",
    "municipality": "MUTISCUA",
    "commune": "54480",
    "address": "CALLE 3N 8-38",
    "classification": "OTROS",
    "sector": "RESTAURANTE YOLY",
    "origin": "GOBERNACION",
    "commercialValue": 58000
  },
  {
    "id": "174023",
    "date": "17/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRR 9 #5-23 LT 7 EDF ROMANO CENTRO",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "MIAMI LICORERIA",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 145600
  },
  {
    "id": "174024",
    "date": "17/10/2024",
    "municipality": "PAMPLONA COLOMBIA",
    "commune": "54518",
    "address": "CRR 9 #5-23 LT 7 EDF ROMANO CENTRO",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "MIAMI LICORERIA",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 40000
  },
  {
    "id": "174018",
    "date": "16/10/2024",
    "municipality": "MUTISCUA",
    "commune": "54480",
    "address": "CRR 2 #8-08 GARAJE",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "VARIEDADES OCHOA",
    "origin": "GOBERNACION",
    "commercialValue": 15000
  },
  {
    "id": "174020",
    "date": "16/10/2024",
    "municipality": "MUTISCUA",
    "commune": "54480",
    "address": "CRR 2 #8-08 GARAJE",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "VARIEDADES OCHOA",
    "origin": "GOBERNACION",
    "commercialValue": 144000
  },
  {
    "id": "174022",
    "date": "16/10/2024",
    "municipality": "MUTISCUA",
    "commune": "54480",
    "address": "CRR 2 #8-08 GARAJE",
    "classification": "OTROS",
    "sector": "VARIEDADES OCHOA",
    "origin": "GOBERNACION",
    "commercialValue": 40000
  },
  {
    "id": "174019",
    "date": "16/10/2024",
    "municipality": "MUTISCUA",
    "commune": "54480",
    "address": "CRR 2 #8-08 GARAJE",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "VARIEDADES OCHOA",
    "origin": "GOBERNACION",
    "commercialValue": 234000
  },
  {
    "id": "174021",
    "date": "16/10/2024",
    "municipality": "MUTISCUA",
    "commune": "54480",
    "address": "CRR 2 #8-08 GARAJE",
    "classification": "OTROS",
    "sector": "VARIEDADES OCHOA",
    "origin": "GOBERNACION",
    "commercialValue": 64000
  },
  {
    "id": "174017",
    "date": "16/10/2024",
    "municipality": "PAMPLONITA",
    "commune": "54520",
    "address": "CALLE 2 CRA 1 ESQUINA",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "TIENDA MIXTA JEAN",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 30000
  },
  {
    "id": "174013",
    "date": "21/10/2024",
    "municipality": "CUCUTA",
    "commune": "5",
    "address": "ANILLO VIAL ORIENTA N4 380 VILLA NIZA",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "ALTIPAL S.A.S.",
    "origin": "GOBERNACION",
    "commercialValue": 1755000
  },
  {
    "id": "174008",
    "date": "21/10/2024",
    "municipality": "CUCUTA",
    "commune": "5",
    "address": "ANILLO VIAL ORIENTA N4 380 VILLA NIZA",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "ALTIPAL S.A.S.",
    "origin": "GOBERNACION",
    "commercialValue": 660000
  },
  {
    "id": "174009",
    "date": "21/10/2024",
    "municipality": "CUCUTA",
    "commune": "5",
    "address": "ANILLO VIAL ORIENTA N4 380 VILLA NIZA",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "ALTIPAL S.A.S.",
    "origin": "GOBERNACION",
    "commercialValue": 2490000
  },
  {
    "id": "174012",
    "date": "21/10/2024",
    "municipality": "CUCUTA",
    "commune": "5",
    "address": "ANILLO VIAL ORIENTA N4 380 VILLA NIZA",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "ALTIPAL S.A.S.",
    "origin": "GOBERNACION",
    "commercialValue": 1320000
  },
  {
    "id": "174015",
    "date": "21/10/2024",
    "municipality": "CUCUTA",
    "commune": "5",
    "address": "ANILLO VIAL ORIENTA N4 380 VILLA NIZA",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "ALTIPAL S.A.S.",
    "origin": "GOBERNACION",
    "commercialValue": 1077000
  },
  {
    "id": "174007",
    "date": "21/10/2024",
    "municipality": "CUCUTA",
    "commune": "5",
    "address": "ANILLO VIAL ORIENTA N4 380 VILLA NIZA",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "ALTIPAL S.A.S.",
    "origin": "GOBERNACION",
    "commercialValue": 17859000
  },
  {
    "id": "174014",
    "date": "21/10/2024",
    "municipality": "CUCUTA",
    "commune": "5",
    "address": "ANILLO VIAL ORIENTA N4 380 VILLA NIZA",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "ALTIPAL S.A.S.",
    "origin": "GOBERNACION",
    "commercialValue": 2019000
  },
  {
    "id": "174011",
    "date": "21/10/2024",
    "municipality": "CUCUTA",
    "commune": "5",
    "address": "ANILLO VIAL ORIENTA N4 380 VILLA NIZA",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "ALTIPAL S.A.S.",
    "origin": "GOBERNACION",
    "commercialValue": 330000
  },
  {
    "id": "174010",
    "date": "21/10/2024",
    "municipality": "CUCUTA",
    "commune": "5",
    "address": "ANILLO VIAL ORIENTA N4 380 VILLA NIZA",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "ALTIPAL S.A.S.",
    "origin": "GOBERNACION",
    "commercialValue": 420000
  },
  {
    "id": "174005",
    "date": "15/10/2024",
    "municipality": "CUCUTA",
    "commune": "2",
    "address": "AV 12E 9 NORTE -38",
    "classification": "OTROS",
    "sector": "SUPERMERCADO GRANJA GUAIMARAL",
    "origin": "GOBERNACION",
    "commercialValue": 70000
  },
  {
    "id": "174006",
    "date": "15/10/2024",
    "municipality": "CUCUTA",
    "commune": "2",
    "address": "AV 12E 9 NORTE -38",
    "classification": "OTROS",
    "sector": "SUPERMERCADO GRANJA GUAIMARAL",
    "origin": "GOBERNACION",
    "commercialValue": 108000
  },
  {
    "id": "174002",
    "date": "02/10/2024",
    "municipality": "LOS PATIOS",
    "commune": "54405",
    "address": "MZ A LT2 URB VALLES DEL MIRADOR",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "TIENDA PIRULITO",
    "origin": "GOBERNACION",
    "commercialValue": 50400
  },
  {
    "id": "174003",
    "date": "02/10/2024",
    "municipality": "LOS PATIOS",
    "commune": "54405",
    "address": "MZ A LT2 URB VALLES DEL MIRADOR",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "TIENDA PIRULITO",
    "origin": "GOBERNACION",
    "commercialValue": 36000
  },
  {
    "id": "174004",
    "date": "02/10/2024",
    "municipality": "LOS PATIOS",
    "commune": "54405",
    "address": "MZ A LT2 URB VALLES DEL MIRADOR",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "TIENDA PIRULITO",
    "origin": "GOBERNACION",
    "commercialValue": 18000
  },
  {
    "id": "174001",
    "date": "11/10/2024",
    "municipality": "BOCHALEMA",
    "commune": "54099",
    "address": "K -105-2",
    "classification": "AGUARDIENTE",
    "sector": "ESTANCO EL PARQUE",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 672000
  },
  {
    "id": "174000",
    "date": "02/10/2024",
    "municipality": "LOS PATIOS",
    "commune": "54405",
    "address": "Norte de Santander, Colombia",
    "classification": "OTROS",
    "sector": "WASH BM",
    "origin": "GOBERNACION",
    "commercialValue": 140000
  },
  {
    "id": "173996",
    "date": "11/10/2024",
    "municipality": "BOCHALEMA",
    "commune": "54099",
    "address": "CLL 7 #3-37 LA ESPERANZA",
    "classification": "OTROS",
    "sector": "CLUB DEPORTIVO LA ROCHELA",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 252000
  },
  {
    "id": "173999",
    "date": "11/10/2024",
    "municipality": "BOCHALEMA",
    "commune": "54099",
    "address": "AV 2 N 3-45",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "BODEGA LOS OLIVOS",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 36000
  },
  {
    "id": "173997",
    "date": "11/10/2024",
    "municipality": "BOCHALEMA",
    "commune": "54099",
    "address": "AV 2 N 3-45",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "BODEGA LOS OLIVOS",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 12000
  },
  {
    "id": "173998",
    "date": "11/10/2024",
    "municipality": "BOCHALEMA",
    "commune": "54099",
    "address": "AV 2 N 3-45",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "BODEGA LOS OLIVOS",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 26000
  },
  {
    "id": "173987",
    "date": "11/10/2024",
    "municipality": "BOCHALEMA",
    "commune": "54099",
    "address": "AV 2 #2-93 BARRIO LA TROJA-DURANIA",
    "classification": "OTROS",
    "sector": "POOLES NIETO",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 78000
  },
  {
    "id": "173990",
    "date": "11/10/2024",
    "municipality": "BOCHALEMA",
    "commune": "54099",
    "address": "AV 2 #2-93 BARRIO LA TROJA-DURANIA",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "POOLES NIETO",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 3000
  },
  {
    "id": "173992",
    "date": "11/10/2024",
    "municipality": "BOCHALEMA",
    "commune": "54099",
    "address": "AV 2 #2-93 BARRIO LA TROJA-DURANIA",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "POOLES NIETO",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 3000
  },
  {
    "id": "173991",
    "date": "11/10/2024",
    "municipality": "BOCHALEMA",
    "commune": "54099",
    "address": "AV 2 #2-93 BARRIO LA TROJA-DURANIA",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "POOLES NIETO",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 3000
  },
  {
    "id": "173988",
    "date": "11/10/2024",
    "municipality": "BOCHALEMA",
    "commune": "54099",
    "address": "AV 2 #2-93 BARRIO LA TROJA-DURANIA",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "POOLES NIETO",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 36000
  },
  {
    "id": "173989",
    "date": "11/10/2024",
    "municipality": "BOCHALEMA",
    "commune": "54099",
    "address": "AV 2 #2-93 BARRIO LA TROJA-DURANIA",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "POOLES NIETO",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 9000
  },
  {
    "id": "173993",
    "date": "11/10/2024",
    "municipality": "BOCHALEMA",
    "commune": "54099",
    "address": "AV 2 #2-93 BARRIO LA TROJA-DURANIA",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "POOLES NIETO",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 3000
  },
  {
    "id": "173986",
    "date": "11/10/2024",
    "municipality": "BOCHALEMA",
    "commune": "54099",
    "address": "CALLE 3 N 3-10",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "FUENTE DE SODA DIANA",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 133000
  },
  {
    "id": "173985",
    "date": "11/10/2024",
    "municipality": "BOCHALEMA",
    "commune": "54099",
    "address": "KDX 109-1 MARCOS GARCIA CARRILLO",
    "classification": "OTROS",
    "sector": "ABASTOS DON JORGE",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 96000
  },
  {
    "id": "173984",
    "date": "11/10/2024",
    "municipality": "BOCHALEMA",
    "commune": "54099",
    "address": "KDX 109-1 MARCOS GARCIA CARRILLO",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "ABASTOS DON JORGE",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 60000
  },
  {
    "id": "173983",
    "date": "11/10/2024",
    "municipality": "BOCHALEMA",
    "commune": "54099",
    "address": "KDX 109-1 MARCOS GARCIA CARRILLO",
    "classification": "AGUARDIENTE",
    "sector": "ABASTOS DON JORGE",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 84000
  },
  {
    "id": "173982",
    "date": "11/10/2024",
    "municipality": "BOCHALEMA",
    "commune": "54099",
    "address": "K 105-2",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "CAFE BAR SARA T",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 14000
  },
  {
    "id": "173979",
    "date": "11/10/2024",
    "municipality": "BOCHALEMA",
    "commune": "54099",
    "address": "K 105-2",
    "classification": "AGUARDIENTE",
    "sector": "CAFE BAR SARA T",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 100000
  },
  {
    "id": "173981",
    "date": "11/10/2024",
    "municipality": "BOCHALEMA",
    "commune": "54099",
    "address": "K 105-2",
    "classification": "OTROS",
    "sector": "CAFE BAR SARA T",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 350000
  },
  {
    "id": "173980",
    "date": "11/10/2024",
    "municipality": "BOCHALEMA",
    "commune": "54099",
    "address": "K 105-2",
    "classification": "AGUARDIENTE",
    "sector": "CAFE BAR SARA T",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 84000
  },
  {
    "id": "173978",
    "date": "11/10/2024",
    "municipality": "BOCHALEMA",
    "commune": "54099",
    "address": "BARRIO CENTRO #2-41 FRENTE AL PARQUEPRINCIPAL",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "ESTANCOTIN",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 54000
  },
  {
    "id": "173977",
    "date": "11/10/2024",
    "municipality": "BOCHALEMA",
    "commune": "54099",
    "address": "AV 2 N 4-42",
    "classification": "CREMA DE LICOR",
    "sector": "TDA EL REY",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 105000
  },
  {
    "id": "173976",
    "date": "11/10/2024",
    "municipality": "BOCHALEMA",
    "commune": "54099",
    "address": "AV 2 N 4-42",
    "classification": "AGUARDIENTE",
    "sector": "TDA EL REY",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 84000
  },
  {
    "id": "173974",
    "date": "11/10/2024",
    "municipality": "BOCHALEMA",
    "commune": "54099",
    "address": "AV 2 N 4-42",
    "classification": "OTROS",
    "sector": "TDA EL REY",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 38000
  },
  {
    "id": "173975",
    "date": "11/10/2024",
    "municipality": "BOCHALEMA",
    "commune": "54099",
    "address": "AV 2 N 4-42",
    "classification": "OTROS",
    "sector": "TDA EL REY",
    "origin": "FUERZA PÚBLICA",
    "commercialValue": 204000
  },
  {
    "id": "173970",
    "date": "09/10/2024",
    "municipality": "CUCUTA",
    "commune": "7",
    "address": "CLL 8 #1C-57 CHAPINERO",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "TM EL CUJI",
    "origin": "GOBERNACION",
    "commercialValue": 420000
  },
  {
    "id": "173971",
    "date": "09/10/2024",
    "municipality": "CUCUTA",
    "commune": "7",
    "address": "CLL 8 #1C-57 CHAPINERO",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "TM EL CUJI",
    "origin": "GOBERNACION",
    "commercialValue": 540000
  },
  {
    "id": "173968",
    "date": "09/10/2024",
    "municipality": "CUCUTA",
    "commune": "7",
    "address": "CLL 8 #1C-57 CHAPINERO",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "TM EL CUJI",
    "origin": "GOBERNACION",
    "commercialValue": 750000
  },
  {
    "id": "173969",
    "date": "09/10/2024",
    "municipality": "CUCUTA",
    "commune": "7",
    "address": "CLL 8 #1C-57 CHAPINERO",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "TM EL CUJI",
    "origin": "GOBERNACION",
    "commercialValue": 300000
  },
  {
    "id": "173972",
    "date": "09/10/2024",
    "municipality": "CUCUTA",
    "commune": "7",
    "address": "CLL 8 #1C-57 CHAPINERO",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "TM EL CUJI",
    "origin": "GOBERNACION",
    "commercialValue": 88000
  },
  {
    "id": "173973",
    "date": "09/10/2024",
    "municipality": "CUCUTA",
    "commune": "7",
    "address": "CLL 8 #1C-57 CHAPINERO",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "TM EL CUJI",
    "origin": "GOBERNACION",
    "commercialValue": 120000
  },
  {
    "id": "173967",
    "date": "09/10/2024",
    "municipality": "CUCUTA",
    "commune": "7",
    "address": "AV 12A -120",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "POOLES MASTER KING",
    "origin": "GOBERNACION",
    "commercialValue": 206800
  },
  {
    "id": "173964",
    "date": "09/10/2024",
    "municipality": "CUCUTA",
    "commune": "7",
    "address": "AV 6N #7A-40 CHAPINERO",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "ESTANCO BARRILES LICORERA",
    "origin": "GOBERNACION",
    "commercialValue": 700000
  },
  {
    "id": "173966",
    "date": "09/10/2024",
    "municipality": "CUCUTA",
    "commune": "7",
    "address": "AV 6N #7A-40 CHAPINERO",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "ESTANCO BARRILES LICORERA",
    "origin": "GOBERNACION",
    "commercialValue": 18000
  },
  {
    "id": "173965",
    "date": "09/10/2024",
    "municipality": "CUCUTA",
    "commune": "7",
    "address": "AV 6N #7A-40 CHAPINERO",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "ESTANCO BARRILES LICORERA",
    "origin": "GOBERNACION",
    "commercialValue": 78400
  },
  {
    "id": "173963",
    "date": "09/10/2024",
    "municipality": "CUCUTA",
    "commune": "10",
    "address": "CALLE 8 AV 3 N1-59",
    "classification": "OTROS",
    "sector": "ESTANCO LA Y DE CUCUTA",
    "origin": "GOBERNACION",
    "commercialValue": 175000
  },
  {
    "id": "173960",
    "date": "09/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "CLL 4 #7-89 VIEJO ESCOBAL",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "MERCADO VIVERES LA FRONTERA",
    "origin": "GOBERNACION",
    "commercialValue": 18000
  },
  {
    "id": "173961",
    "date": "09/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "CLL 4 #7-89 VIEJO ESCOBAL",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "MERCADO VIVERES LA FRONTERA",
    "origin": "GOBERNACION",
    "commercialValue": 175000
  },
  {
    "id": "173962",
    "date": "09/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "CLL 4 #7-89 VIEJO ESCOBAL",
    "classification": "OTROS",
    "sector": "MERCADO VIVERES LA FRONTERA",
    "origin": "GOBERNACION",
    "commercialValue": 114000
  },
  {
    "id": "173955",
    "date": "08/10/2024",
    "municipality": "CUCUTA",
    "commune": "6",
    "address": "AV 3 #219-19 APTO 102 URB GARCIA HERREROS",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "BEER STAR COLMBIA",
    "origin": "GOBERNACION",
    "commercialValue": 17500
  },
  {
    "id": "173959",
    "date": "08/10/2024",
    "municipality": "CUCUTA",
    "commune": "6",
    "address": "AV 3 #219-19 APTO 102 URB GARCIA HERREROS",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "BEER STAR COLMBIA",
    "origin": "GOBERNACION",
    "commercialValue": 6000
  },
  {
    "id": "173957",
    "date": "08/10/2024",
    "municipality": "CUCUTA",
    "commune": "6",
    "address": "AV 3 #219-19 APTO 102 URB GARCIA HERREROS",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "BEER STAR COLMBIA",
    "origin": "GOBERNACION",
    "commercialValue": 44800
  },
  {
    "id": "173958",
    "date": "08/10/2024",
    "municipality": "CUCUTA",
    "commune": "6",
    "address": "AV 3 #219-19 APTO 102 URB GARCIA HERREROS",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "BEER STAR COLMBIA",
    "origin": "GOBERNACION",
    "commercialValue": 5000
  },
  {
    "id": "173956",
    "date": "08/10/2024",
    "municipality": "CUCUTA",
    "commune": "6",
    "address": "AV 3 #219-19 APTO 102 URB GARCIA HERREROS",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "BEER STAR COLMBIA",
    "origin": "GOBERNACION",
    "commercialValue": 135000
  },
  {
    "id": "173952",
    "date": "08/10/2024",
    "municipality": "CUCUTA",
    "commune": "6",
    "address": "CALLE 14 N 3-123",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "DISTRIBUIDORA MEAT MARKE EXPRESS S.A.S",
    "origin": "GOBERNACION",
    "commercialValue": 28000
  },
  {
    "id": "173954",
    "date": "08/10/2024",
    "municipality": "CUCUTA",
    "commune": "6",
    "address": "CALLE 14 N 3-123",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "DISTRIBUIDORA MEAT MARKE EXPRESS S.A.S",
    "origin": "GOBERNACION",
    "commercialValue": 40000
  },
  {
    "id": "173953",
    "date": "08/10/2024",
    "municipality": "CUCUTA",
    "commune": "6",
    "address": "CALLE 14 N 3-123",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "DISTRIBUIDORA MEAT MARKE EXPRESS S.A.S",
    "origin": "GOBERNACION",
    "commercialValue": 8400
  },
  {
    "id": "173951",
    "date": "08/10/2024",
    "municipality": "CUCUTA",
    "commune": "6",
    "address": "CLL 19 #2-101 APTO 1 URB GARCIA HERREROS",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "FUENTE DE SODA EL CHORRO 2",
    "origin": "GOBERNACION",
    "commercialValue": 22500
  },
  {
    "id": "173949",
    "date": "08/10/2024",
    "municipality": "CUCUTA",
    "commune": "6",
    "address": "CLL 19 #2-101 APTO 1 URB GARCIA HERREROS",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "FUENTE DE SODA EL CHORRO 2",
    "origin": "GOBERNACION",
    "commercialValue": 42900
  },
  {
    "id": "173950",
    "date": "08/10/2024",
    "municipality": "CUCUTA",
    "commune": "6",
    "address": "CLL 19 #2-101 APTO 1 URB GARCIA HERREROS",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "FUENTE DE SODA EL CHORRO 2",
    "origin": "GOBERNACION",
    "commercialValue": 30000
  },
  {
    "id": "173948",
    "date": "08/10/2024",
    "municipality": "CUCUTA",
    "commune": "6",
    "address": "CLL 13 #2-06 URB GARCIA HERREROS",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "BILLAR GENY",
    "origin": "GOBERNACION",
    "commercialValue": 8400
  },
  {
    "id": "173947",
    "date": "08/10/2024",
    "municipality": "CUCUTA",
    "commune": "6",
    "address": "CLL 13 #2-06 URB GARCIA HERREROS",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "BILLAR GENY",
    "origin": "GOBERNACION",
    "commercialValue": 162500
  },
  {
    "id": "173943",
    "date": "07/10/2024",
    "municipality": "CUCUTA",
    "commune": "3",
    "address": "AV 17 #25-20 AGUAS CALIENTES",
    "classification": "OTROS",
    "sector": "DEPOSITO 24/7",
    "origin": "GOBERNACION",
    "commercialValue": 28000
  },
  {
    "id": "173942",
    "date": "07/10/2024",
    "municipality": "CUCUTA",
    "commune": "3",
    "address": "AV 17 #25-20 AGUAS CALIENTES",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "DEPOSITO 24/7",
    "origin": "GOBERNACION",
    "commercialValue": 74800
  },
  {
    "id": "173946",
    "date": "07/10/2024",
    "municipality": "CUCUTA",
    "commune": "3",
    "address": "AV 17 #25-20 AGUAS CALIENTES",
    "classification": "OTROS",
    "sector": "DEPOSITO 24/7",
    "origin": "GOBERNACION",
    "commercialValue": 1691000
  },
  {
    "id": "173945",
    "date": "07/10/2024",
    "municipality": "CUCUTA",
    "commune": "3",
    "address": "AV 17 #25-20 AGUAS CALIENTES",
    "classification": "OTROS",
    "sector": "DEPOSITO 24/7",
    "origin": "GOBERNACION",
    "commercialValue": 88000
  },
  {
    "id": "173941",
    "date": "07/10/2024",
    "municipality": "CUCUTA",
    "commune": "3",
    "address": "AV 17 #25-20 AGUAS CALIENTES",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "DEPOSITO 24/7",
    "origin": "GOBERNACION",
    "commercialValue": 24000
  },
  {
    "id": "173944",
    "date": "07/10/2024",
    "municipality": "CUCUTA",
    "commune": "3",
    "address": "AV 17 #25-20 AGUAS CALIENTES",
    "classification": "OTROS",
    "sector": "DEPOSITO 24/7",
    "origin": "GOBERNACION",
    "commercialValue": 60000
  },
  {
    "id": "173937",
    "date": "07/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "CLL 10 #18-29",
    "classification": "OTROS",
    "sector": "ABASTOS LA 10",
    "origin": "GOBERNACION",
    "commercialValue": 90000
  },
  {
    "id": "173940",
    "date": "07/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "CLL 10 #18-29",
    "classification": "WHISKY",
    "sector": "ABASTOS LA 10",
    "origin": "GOBERNACION",
    "commercialValue": 90000
  },
  {
    "id": "173939",
    "date": "07/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "CLL 10 #18-29",
    "classification": "OTROS",
    "sector": "ABASTOS LA 10",
    "origin": "GOBERNACION",
    "commercialValue": 20000
  },
  {
    "id": "173938",
    "date": "07/10/2024",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "CLL 10 #18-29",
    "classification": "OTROS",
    "sector": "ABASTOS LA 10",
    "origin": "GOBERNACION",
    "commercialValue": 10000
  },
  {
    "id": "173934",
    "date": "04/10/2024",
    "municipality": "CUCUTA",
    "commune": "8",
    "address": "MZ R1 LT 18-2 ETAPA 1 ATALAYA",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "LICORERIA EL RINCON",
    "origin": "GOBERNACION",
    "commercialValue": 294000
  },
  {
    "id": "173935",
    "date": "04/10/2024",
    "municipality": "CUCUTA",
    "commune": "8",
    "address": "MZ R1 LT 18-2 ETAPA 1 ATALAYA",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "LICORERIA EL RINCON",
    "origin": "GOBERNACION",
    "commercialValue": 30000
  },
  {
    "id": "173936",
    "date": "04/10/2024",
    "municipality": "CUCUTA",
    "commune": "8",
    "address": "MZ R1 LT 18-2 ETAPA 1 ATALAYA",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "LICORERIA EL RINCON",
    "origin": "GOBERNACION",
    "commercialValue": 150000
  },
  {
    "id": "173908",
    "date": "04/10/2024",
    "municipality": "CUCUTA",
    "commune": "8",
    "address": "CL 5N #21B-03 MZ I4 LT 19 ATALAYA ETAPA 1",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "HIELERA BLUE ATALAYA",
    "origin": "GOBERNACION",
    "commercialValue": 21000
  },
  {
    "id": "173907",
    "date": "04/10/2024",
    "municipality": "CUCUTA",
    "commune": "8",
    "address": "CL 5N #21B-03 MZ I4 LT 19 ATALAYA ETAPA 1",
    "classification": "OTROS",
    "sector": "HIELERA BLUE ATALAYA",
    "origin": "GOBERNACION",
    "commercialValue": 64000
  },
  {
    "id": "173909",
    "date": "04/10/2024",
    "municipality": "CUCUTA",
    "commune": "8",
    "address": "CL 5N #21B-03 MZ I4 LT 19 ATALAYA ETAPA 1",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "HIELERA BLUE ATALAYA",
    "origin": "GOBERNACION",
    "commercialValue": 90000
  },
  {
    "id": "173903",
    "date": "03/10/2024",
    "municipality": "CUCUTA",
    "commune": "8",
    "address": "CLL 23 #51-85 ANTONIA SANTOS",
    "classification": "APERITIVO NO VÍNICO",
    "sector": "TIENDA DOÑA MARTHA",
    "origin": "GOBERNACION",
    "commercialValue": 52000
  },
  {
    "id": "173885",
    "date": "03/10/2024",
    "municipality": "CUCUTA",
    "commune": "7",
    "address": "MZ 4J LT 1 TUCUNARE",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "MAKEYN",
    "origin": "GOBERNACION",
    "commercialValue": 78000
  },
  {
    "id": "173884",
    "date": "03/10/2024",
    "municipality": "CUCUTA",
    "commune": "7",
    "address": "MZ 4J LT 1 TUCUNARE",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "MAKEYN",
    "origin": "GOBERNACION",
    "commercialValue": 72000
  },
  {
    "id": "173883",
    "date": "02/10/2024",
    "municipality": "CUCUTA",
    "commune": "7",
    "address": "MZ 4 LT 5 TUCUNARE",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "TIENDA DE TODITO",
    "origin": "GOBERNACION",
    "commercialValue": 80000
  },
  {
    "id": "173881",
    "date": "02/10/2024",
    "municipality": "CUCUTA",
    "commune": "8",
    "address": "MZ 14 LT 16 PALMERAS PARTE ALTA",
    "classification": "OTROS",
    "sector": "SUPERMERCADO TRIGAL",
    "origin": "GOBERNACION",
    "commercialValue": 90000
  },
  {
    "id": "173882",
    "date": "02/10/2024",
    "municipality": "CUCUTA",
    "commune": "8",
    "address": "MZ 14 LT 16 PALMERAS PARTE ALTA",
    "classification": "APERITIVO NO VÍNICO",
    "sector": "SUPERMERCADO TRIGAL",
    "origin": "GOBERNACION",
    "commercialValue": 1278000
  },
  {
    "id": "173879",
    "date": "02/10/2024",
    "municipality": "CUCUTA",
    "commune": "7",
    "address": "MZ LT 1 TUCUNARE",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "TIENDA MIXTA DARY LUZ",
    "origin": "GOBERNACION",
    "commercialValue": 30000
  },
  {
    "id": "173880",
    "date": "02/10/2024",
    "municipality": "CUCUTA",
    "commune": "7",
    "address": "MZ LT 1 TUCUNARE",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "TIENDA MIXTA DARY LUZ",
    "origin": "GOBERNACION",
    "commercialValue": 105000
  },
  {
    "id": "173472",
    "date": "01/10/2024",
    "municipality": "CUCUTA",
    "commune": "8",
    "address": "AV 3 #8-02 BARRIO NIDIA",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "INVERSIONES J Y K PLUS S.A.S.",
    "origin": "GOBERNACION",
    "commercialValue": 2130000
  },
  {
    "id": "173473",
    "date": "01/10/2024",
    "municipality": "CUCUTA",
    "commune": "8",
    "address": "AV 3 #8-02 BARRIO NIDIA",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "INVERSIONES J Y K PLUS S.A.S.",
    "origin": "GOBERNACION",
    "commercialValue": 60000
  },
  {
    "id": "173466",
    "date": "01/10/2024",
    "municipality": "CUCUTA",
    "commune": "8",
    "address": "MZ 7 2A-52 EL OASIS AV 7 #2A-52",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "MARIA RAMIREZ",
    "origin": "GOBERNACION",
    "commercialValue": 123000
  },
  {
    "id": "173468",
    "date": "01/10/2024",
    "municipality": "CUCUTA",
    "commune": "8",
    "address": "MZ 7 2A-52 EL OASIS AV 7 #2A-52",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "MARIA RAMIREZ",
    "origin": "GOBERNACION",
    "commercialValue": 30000
  },
  {
    "id": "173471",
    "date": "01/10/2024",
    "municipality": "CUCUTA",
    "commune": "8",
    "address": "MZ 7 2A-52 EL OASIS AV 7 #2A-52",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "MARIA RAMIREZ",
    "origin": "GOBERNACION",
    "commercialValue": 9000
  },
  {
    "id": "173470",
    "date": "01/10/2024",
    "municipality": "CUCUTA",
    "commune": "8",
    "address": "MZ 7 2A-52 EL OASIS AV 7 #2A-52",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "MARIA RAMIREZ",
    "origin": "GOBERNACION",
    "commercialValue": 9000
  },
  {
    "id": "173467",
    "date": "01/10/2024",
    "municipality": "CUCUTA",
    "commune": "8",
    "address": "MZ 7 2A-52 EL OASIS AV 7 #2A-52",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "MARIA RAMIREZ",
    "origin": "GOBERNACION",
    "commercialValue": 72000
  },
  {
    "id": "173469",
    "date": "01/10/2024",
    "municipality": "CUCUTA",
    "commune": "8",
    "address": "MZ 7 2A-52 EL OASIS AV 7 #2A-52",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "MARIA RAMIREZ",
    "origin": "GOBERNACION",
    "commercialValue": 30000
  },
  {
    "id": "173457",
    "date": "01/10/2024",
    "municipality": "CUCUTA",
    "commune": "8",
    "address": "CLL 6A #24-10",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "MINI ABASTOS EL DIAMANTE",
    "origin": "GOBERNACION",
    "commercialValue": 12000
  },
  {
    "id": "173458",
    "date": "01/10/2024",
    "municipality": "CUCUTA",
    "commune": "8",
    "address": "CLL 6A #24-10",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "MINI ABASTOS EL DIAMANTE",
    "origin": "GOBERNACION",
    "commercialValue": 60000
  },
  {
    "id": "173459",
    "date": "01/10/2024",
    "municipality": "CUCUTA",
    "commune": "8",
    "address": "CLL 6A #24-10",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "MINI ABASTOS EL DIAMANTE",
    "origin": "GOBERNACION",
    "commercialValue": 45000
  },
  {
    "id": "173456",
    "date": "01/10/2024",
    "municipality": "CUCUTA",
    "commune": "8",
    "address": "CLL 6A #24-10",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "MINI ABASTOS EL DIAMANTE",
    "origin": "GOBERNACION",
    "commercialValue": 27000
  },
  {
    "id": "173453",
    "date": "01/10/2024",
    "municipality": "CUCUTA",
    "commune": "8",
    "address": "CLL 6A #21-20",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "TIENDA EMILIANO",
    "origin": "GOBERNACION",
    "commercialValue": 30000
  },
  {
    "id": "173452",
    "date": "01/10/2024",
    "municipality": "CUCUTA",
    "commune": "8",
    "address": "CLL 6A #21-20",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "TIENDA EMILIANO",
    "origin": "GOBERNACION",
    "commercialValue": 48000
  },
  {
    "id": "173449",
    "date": "01/10/2024",
    "municipality": "CUCUTA",
    "commune": "8",
    "address": "CLL 6A #21-20",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "TIENDA EMILIANO",
    "origin": "GOBERNACION",
    "commercialValue": 6000
  },
  {
    "id": "173450",
    "date": "01/10/2024",
    "municipality": "CUCUTA",
    "commune": "8",
    "address": "CLL 6A #21-20",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "TIENDA EMILIANO",
    "origin": "GOBERNACION",
    "commercialValue": 12000
  },
  {
    "id": "173451",
    "date": "01/10/2024",
    "municipality": "CUCUTA",
    "commune": "8",
    "address": "CLL 6A #21-20",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "TIENDA EMILIANO",
    "origin": "GOBERNACION",
    "commercialValue": 12000
  },
  {
    "id": "173448",
    "date": "01/10/2024",
    "municipality": "CUCUTA",
    "commune": "8",
    "address": "CLL 6A #21-20",
    "classification": "CIGARRILLOS Y TABACOS",
    "sector": "TIENDA EMILIANO",
    "origin": "GOBERNACION",
    "commercialValue": 27000
  },
  {
    "id": "175001",
    "date": "10/09/2025",
    "municipality": "CUCUTA",
    "commune": "4",
    "address": "CLL 18A #9-02 LA LIBERTAD CUCUTA",
    "classification": "CERVEZAS, SIFONES, REFAJOS Y MEZCLAS",
    "sector": "ESTANCO HIELOS Y LICORES LA 9",
    "origin": "GOBERNACION",
    "commercialValue": 18000
  }
];

export const apprehensions: Apprehension[] = rawData.map((item) => {
    const coords = getCoords(item.municipality, item.id);
    return {
        ...item,
        date: parseDate(item.date),
        lat: coords.lat,
        lng: coords.lng
    };
});
